// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from 'prisma/config'
import * as dotenv from 'dotenv'

dotenv.config()

export default defineConfig({
  earlyAccess: true,
  schema: 'prisma/schema.prisma',

  datasource: {
    url: process.env.DATABASE_URL,
  },

  migrate: {
    adapter: async () => {
      const { PrismaNeon } = await import('@prisma/adapter-neon')
      const { neonConfig, Pool } = await import('@neondatabase/serverless')
      const ws = await import('ws')
      neonConfig.webSocketConstructor = ws.default
      const pool = new Pool({ connectionString: process.env.DATABASE_URL })
      return new PrismaNeon(pool)
    },
  },
})